### ISSUE TITLE
tracetest fails to compile in C++

### ISSUE THREAD

**Issue by isaachier** [jaegertracing/jaeger-idl#35]
[tracetest.thrift](https://github.com/uber/jaeger-idl/blob/master/thrift/crossdock/tracetest.thrift#L11) declares a recursive member in its struct. I have found the generated code fails to compile in C++. It seems Thrift does not support any sort of recursive types as far as I can tell. What is the best way to fix/address this?

**Comment by yurishkuro** [comment]
I haven't used C++ for a while, but isn't there a way to pre-declare the type so that you can declare a pointer to it? what does the code look like?

**Comment by isaachier** [comment]
I saw something called `cpp_type` for Thrift which could help here. Usually the solution would be to use a pointer to the type instead of the actual type. Thrift doesn't seem to directly allow that.

Example:

```cpp
struct Downstream {
  //...
  Downstream* downstream;
};
```

**Comment by isaachier** [comment]
Actually, looking at the file it is clear to me that `Downstream` can probably be wrapped in a list without the last member. Not sure how to do this without breaking backwards compatibility with other clients.

**Comment by isaachier** [comment]
And for the record: https://stackoverflow.com/q/15634101/1930331.

**Comment by isaachier** [comment]
One last thought. The reason this only fails in C++ and not any other language relates to the way `optional` is implemented in C++. Unlike Go, `optional` does not generate a pointer member in C++. Instead, the generated code looks something like this:

```thrift
struct Foo {
    2: optional string text
}
```

```cpp
typedef struct _Foo__isset {
    bool bar :1;
} _Foo_isset;

class Foo {
    Bar bar;
    _Foo__isset __isset;

    void __set_bar(const Bar& b) { bar = b; __isset.bar = true; }
};
```

**Comment by isaachier** [comment]
@yurishkuro this might block C++ client crossdock testing if it cannot be changed.

**Comment by yurishkuro** [comment]
can we fudge the generated files?  Changing tracetest API is not impossible, but rather involved, we'd need to do it across all clients, unless the IDL change can be made compatible with the existing format.

**Comment by isaachier** [comment]
Ya that is fine with me. Might be worth noting as a "TODO." Newer versions of Thrift fix this, but not 0.9.2.

**Comment by yurishkuro** [comment]
why do you need 0.9.2?  I believe you can use 0.9.3 or 0.10, they are compatible in the actual payloads, just the language APIs are different, which is not a problem for you.

**Comment by isaachier** [comment]
In that case why are we using it across the board when using jaeger-idl?

**Comment by yurishkuro** [comment]
IIRC we only use 0.9.2 in Java, for legacy reasons. Go uses 0.9.3, JS/Python don't use Thrift at all (they use thriftrw).

**Comment by isaachier** [comment]
I see. Lol if I had known this before I wouldn't have bothered with
downgrading to 0.9.2 and adding it to the package manager (
https://github.com/hunter-packages/thrift/pull/3). I think this might make
it easier on those relying on older versions of Thrift to integrate with
Jaeger but I might be wrong.

**Comment by yurishkuro** [comment]
is there a way to shadow/vendor thrift code in C++ so that it doesn't conflict with people's dependencies?

**Comment by isaachier** [comment]
Although that sounds simple, it is pretty difficult to do properly. The
package manager I have been using (Hunter) is able to do this, but I'm not
sure if most users will want to use it.

**Comment by isaachier** [comment]
I'm wondering how this is done in any compiled language. When linking together an executable, the linker doesn't care where the symbols come from, as long as they are resolved. Even if I make a library that included the Thrift library sources, wouldn't the linker ultimately discard the symbols that it doesn't need?

Example:
`g++ -o myapp -L/path/to/thrift-0.9.2 -ljaegertracing -L/path/to/jaeger -ljaegertracing -L/path/to/thrift-0.10.0`

The above case will probably drop the symbols in Thrift 0.10.0 in favor of the existing symbols in Thrift 0.9.2.

**Comment by yurishkuro** [comment]
In Java this is achieved via "shading" which rewrites the package name of the included module, e.g. instead of `com.guava` you would have `io.jaeger.shade.com.guava` in the final JAR.

In Go I've seen people simply copying the vendored code into a sub-dir, which also results in a separate package name.

Of course this approach only works if the shaded packages are not exposed via your module's public API.

**Comment by isaachier** [comment]
OK I see. Java and Go both actually define symbols with the path as a prefix/namespace. In C++ this all has to be done by hand. Unfortunately, libraries rarely do anything like that. An example of how that could be accomplished.

```cpp
namespace v2 {
namespace apache {
namespace thrift {
// ...
}
}
}
```

More often they are actually included in a separate directory and linked with a different library.

**Comment by isaachier** [comment]
Still a problem, but fixed temporarily with this: https://github.com/isaachier/cpp-client/commit/10719ae66144ac68baf0ad6a08d95f89dee95601.

**Comment by isaachier** [comment]
Just going to resolve this for now.

**Comment by ringerc** [comment]
This is different to the Thrift pull req in https://github.com/apache/thrift/pull/84, since that didn't address optional self-membership.

I've opened a new Thrift bug https://issues.apache.org/jira/browse/THRIFT-4484 .

This blocks code-generation for the c++ library. It has to apply a manual patch to the generated code right now, making it hard to use other Thrift versions, automate builds more, etc.

What would the consequences of changing how this is modeled in the IDL be?

**Comment by ringerc** [comment]
@yurishkuro OK, good to know. Unfortunately it looks like `zipkincore.thrift` is affected too; unsure if working around that with an IDL change introduces a compatibility issue with zipkin.

Ideally Thrift would just generate sane C++...

**Comment by ringerc** [comment]
The fix to the IDL is trivial. I don't know Thrift well enough (or at all) so can't say if it will affect the wire format, but I'm guessing not?

More of a concern is whether it affects the other bindings' generated code. See https://github.com/ringerc/jaeger-idl/pull/1 .

**Comment by isaachier** [comment]
@yurishkuro reminded me a while back that the Thrift wire protocol is unlikely to change at all between minor versions of Thrift. The only changes will be the headers used etc. I only use 0.9.2 for an internal Uber project. Otherwise, if a later version supports recursive types, feel free to use that version instead. As I have pointed out before, please ignore Zipkin entirely if possible. I understand that there is a method using a Thrift type as an argument, but the argument is unused and should not be needed for compilation.

**Comment by ringerc** [comment]
Good to know. The latest Thrift also chokes on this IDL and produces bad
C++, though.

It looks like using a by-reference member isn't enough, Thrift generates
differently wacky C++ where it tries to access members of `__isset` e.g.
`this->downstream->__isset.serviceName`. Looking into it.

**Comment by ringerc** [comment]
It looks like the problem IDL is confined to use by Crossdock, not the main protocol and project.

So Jaeger should probably just patch it to something Thrift doesn't choke on.

**Comment by ringerc** [comment]
This is a blocker for making the cpp-client work on a Thrift other than 0.9.2. Since Thrift 0.9.2 doesn't support openssl 1.1, it's a pretty major source of pain.

The bad IDL only appears to affect Zipkin support and Crossdock support, so the impact of fixing it even if it makes a wire protocol change will only affect users of those features.

Please?

In the mean time I've ripped out Zipkin and Crossdock support from jaeger `cpp-client` so I can build it on Thrift 0.11.0 and OpenSSL 1.1; see https://github.com/jaegertracing/cpp-client/pull/61 for the working branch. This is not mergeable.

**Comment by ringerc** [comment]
Ping @yurishkuro for practicality of removing the faulty `optional` self-referential usage from the IDL.

**Comment by isaachier** [comment]
I don't see the need to change the type. If anything, I heard more recent versions of Thrift support the recursive references.

**Comment by ringerc** [comment]
I tried it. They support the recursive references, but they generate bad
code when a recursive reference is declared 'optional'.​ See above-linked
Thrift bug.

I guess I could try to fix Thrift, but then we'd be stuck waiting for a
release, and I'd probably just go further down the rabbit hole.

**Comment by ringerc** [comment]
When I tested Thrift 0.11.0 it produced *differently wrong* results. I'll check.
