### ISSUE TITLE
trouble in the way of pb to thrift

### ISSUE THREAD

**Issue by wxyu9191** [jaegertracing/jaeger-idl#51]
hey guys, help me please !!!  I meet the same question in thrift. when I try to make it, it shows error like this:make[3]: Entering directory `/home/worker/thrift/thrift/compiler/cpp/src'
/bin/sh ../../../ylwrap thrift/thrifty.yy y.tab.c thrift/thrifty.cc y.tab.h `echo thrift/thrifty.cc | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output thrift/thrifty.output -- byacc -d 
byacc: e - line 1 of "/home/worker/thrift/thrift/compiler/cpp/src/thrift/thrifty.yy", syntax error
%code requires {
^

do you have some mind

**Comment by yurishkuro** [comment]
It looks like you are trying to compile thriftc from source? We don't do that, we just use a prebuilt Docker image. You may want to address your question to thrift support channels.
