### ISSUE TITLE
Migrate .proto files from the main repository

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-idl#55]
The main blocker is we need to find a way to automatically remove gogo annotations from .proto files, OR prepare a build tool-chain (e.g. a Docker image) where all gogo plugins are installed and it can be used to generate code for other languages.

Related issues:
  * https://github.com/jaegertracing/jaeger/issues/1484 "add protobuf model to jaeger-idl"
  * https://github.com/jaegertracing/jaeger/issues/1213 "ignore gogo annotations"

**Comment by zoidbergwill** [comment]
I'm keen to help with a build tool-chain Docker image that can build them, based on the discussion here and in https://github.com/jaegertracing/jaeger/issues/1484

**Comment by pavolloffay** [comment]
@zoidbergwill that is great! Go head.
