### ISSUE TITLE
Retrieve Traces using gRpc

### ISSUE THREAD

**Issue by shaikadilmd** [jaegertracing/jaeger-idl#71]
Hello All,

I do know how to retrieve the trace from jaeger using TraceID with help of curl command. Can anyone suggest here how to do the same using gRPc. It will greatly help in my research.

**Comment by joe-elliott** [comment]
I have not done it myself but the querier implements the [QueryService](https://github.com/jaegertracing/jaeger-idl/blob/master/proto/api_v2/query.proto#L127) here:

https://github.com/jaegertracing/jaeger/blob/master/cmd/query/app/grpc_handler.go#L45

So I believe just building a client and issuing requests to the jaeger-query component should work.

**Comment by shaikadilmd** [comment]
Hi Joe,

We use DeathStarBench microservices benchmark which is famous for benchmarking and uses Jaeger UI for trace information. I believe it does not have the querier or anything to implement the QueryService. 

But, I will check. Thank you for your suggestions. It will help.
