### ISSUE TITLE
Steps to generate files for python

### ISSUE THREAD

**Issue by lavender04** [jaegertracing/jaeger-idl#83]
Hey,

I'm trying to generate all needed python files to use the gRPC api inside my own python project. I've seen that @lonewolf3739 has fixed some generation problems (https://github.com/jaegertracing/jaeger-client-csharp/issues/197, https://githubmemory.com/repo/jaegertracing/docker-protobuf/issues).
After all I'm struggling on how to do it at all.

I've generated a `model_pb2.py` and a `query_pb2.py` file. As soon as I tried to use them in my code it throws an `ModuleNotFoundError: No module named 'gogoproto'`
Next I've generated the dependency code. `gogo_pb2.py` is now located in the same location as the files above.
I'm still getting the `ModuleNotFoundError`

Could someone explain me how to structure the files correctly?

**Comment by pavolloffay** [comment]
I haven't tried this for python, but here is an example for java `https://github.com/jaegertracing/docker-protobuf#generate-dependencies`. 

Maybe the location of generated files is wrong. 

Alternatively, you could link gogo from here https://github.com/sanlengjingvv/gogo-python, but I would recommend generating them instead.

**Comment by lavender04** [comment]
I needed to delete all references of `gogoproto` in the above files by hand. Then it worked. Not really handy....
