### ISSUE TITLE
Bump the opentracing-proto submodule to fix go bindings

### ISSUE THREAD

**Issue by gordallott** [jaegertracing/jaeger-idl#90]
**Describe the bug**
The go bindings have been broken for a while because of upstream changes in open-telemetry/opentracing - they recently merged a [PR]((https://github.com/open-telemetry/opentelemetry-proto/pull/360)) that will fix golang bindings built from their .proto files 

**To Reproduce**
1. make proto
2. oh no the golang proto files don't build

**Expected behavior**
The proto files to build 

**Screenshots**
nope

**Version (please complete the following information):**
 - OS: linux
 - Jaeger version: 
 - Deployment:

**What troubleshooting steps did you try?**

**Additional context**
the cause was the upstream proto files depending on generated go that didn't exist anywhere publicly, they now import the correct repository 

The opentracing-proto submodule needs to be bumped to (at least) open-telemetry/opentelemetry-proto@0e254b5c04614244edb35a9d4bf73ca26b44438a

I avoided just making a PR to do this because I'm unsure of any other changes that might affect this repository

**Comment by gordallott** [comment]
`make proto` works, it builds the files - the problem is it generates incorrect go code as detailed above. specifically the imports are wrong because of a mistake on part of open-telemetry/opentelemetry-proto

**Comment by yurishkuro** [comment]
cc @albertteoh 

I see that in the main Jaeger repo we have `./otel_proto_patch.sed` that rewrites some of the parts in the file
