### ISSUE TITLE
Unclear documentation for max, minDuration for traces endpoint

### ISSUE THREAD

**Issue by kevinburkesegment** [jaegertracing/jaeger-idl#93]
A trace is a collection of multiple spans. What does it mean to pass `maxDuration` or `minDuration` to the `/api/traces` endpoint? The documentation says: 

> minDuration: Ex. 100000 (for 100ms). Only return traces whose `Span.duration` is greater than or equal to minDuration microseconds.
> maxDuration: Only return traces whose Span.duration is less than or equal to `maxDuration` microseconds. Only valid with minDuration.

Must all spans in a trace be larger than `minDuration`, if set? Must only one span in a trace fit within the min and max duration parameters? It's not really obvious what the intention is here.

**Comment by yurishkuro** [comment]
The zipkin files are just a copy from the Zipkin project, we're not going to change them.

**Comment by kevinburkesegment** [comment]
OK - can you point me to the right place to file a ticket?

**Comment by yurishkuro** [comment]
probably here https://github.com/openzipkin/zipkin-api
