### ISSUE TITLE
[Bug]: model/proto incorrect golang package

### ISSUE THREAD

**Issue by Pwalne** [jaegertracing/jaeger-idl#96]
### What happened?

The golang package of `model.proto` should be `api_v2`. There is even a comment that states this...

### Steps to reproduce

1. Generate golang protobuf
2. Notice it has a package of `model`.

### Expected behavior

The golang protobuf should compile without errors.

**Comment by yurishkuro** [comment]
Not planning to fix this. If you want to provide a PR to jaeger repo that will make the change in-place before generating data model, I'd be open to it.
